Repository PI-coffeeBreak/pi-coffeebreak.github.io, pull requests merged in 2025-03, with the labels that each got.

#1 SCRUM-39-Add-calendar-to-website
  package-lock.json
  src/pages/calendar.md
  src/pages/calendar.mdx
Labels: enhancement

#3 Add minutes 2 & 3
  public/docs/Minute2.pdf
  public/docs/Minute3.pdf
  src/pages/minutes.astro
Labels: Minutes

#4 Funtional Requirements
  src/pages/elaboration.mdx
Labels: documentation

#5 Scrum 75 add non functional requirements to elaboration site
  src/pages/elaboration.mdx
Labels: documentation
